#include "engine/input/keyboard_map.hpp"

namespace engine
{
    namespace input
    {
        const std::unordered_map<int, Key> GlfwKeycodeToEngineKey = {
            {GLFW_KEY_0, Key::k0},
            {GLFW_KEY_1, Key::k1},
            {GLFW_KEY_2, Key::k2},
            {GLFW_KEY_3, Key::k3},
            {GLFW_KEY_4, Key::k4},
            {GLFW_KEY_5, Key::k5},
            {GLFW_KEY_6, Key::k6},
            {GLFW_KEY_7, Key::k7},
            {GLFW_KEY_8, Key::k8},
            {GLFW_KEY_9, Key::k9},
            {GLFW_KEY_A, Key::kA},
            {GLFW_KEY_B, Key::kB},
            {GLFW_KEY_C, Key::kC},
            {GLFW_KEY_D, Key::kD},
            {GLFW_KEY_E, Key::kE},
            {GLFW_KEY_F, Key::kF},
            {GLFW_KEY_G, Key::kG},
            {GLFW_KEY_H, Key::kH},
            {GLFW_KEY_I, Key::kI},
            {GLFW_KEY_J, Key::kJ},
            {GLFW_KEY_K, Key::kK},
            {GLFW_KEY_L, Key::kL},
            {GLFW_KEY_M, Key::kM},
            {GLFW_KEY_N, Key::kN},
            {GLFW_KEY_O, Key::kO},
            {GLFW_KEY_P, Key::kP},
            {GLFW_KEY_Q, Key::kQ},
            {GLFW_KEY_R, Key::kR},
            {GLFW_KEY_S, Key::kS},
            {GLFW_KEY_T, Key::kT},
            {GLFW_KEY_U, Key::kU},
            {GLFW_KEY_V, Key::kV},
            {GLFW_KEY_W, Key::kW},
            {GLFW_KEY_X, Key::kX},
            {GLFW_KEY_Y, Key::kY},
            {GLFW_KEY_Z, Key::kZ},

            {GLFW_KEY_APOSTROPHE, Key::kApostrophe},
            {GLFW_KEY_BACKSLASH, Key::kBackslash},
            {GLFW_KEY_COMMA, Key::kComma},
            {GLFW_KEY_EQUAL, Key::kEqual},
            {GLFW_KEY_GRAVE_ACCENT, Key::kGraveAccent},
            {GLFW_KEY_LEFT_BRACKET, Key::kLeftBracket},
            {GLFW_KEY_MINUS, Key::kMinus},
            {GLFW_KEY_PERIOD, Key::kPeriod},
            {GLFW_KEY_RIGHT_BRACKET, Key::kRightBracket},
            {GLFW_KEY_SEMICOLON, Key::kSemicolon},
            {GLFW_KEY_SLASH, Key::kSlash},
            {GLFW_KEY_WORLD_2, Key::kWorld2},

            {GLFW_KEY_BACKSPACE, Key::kBackspace},
            {GLFW_KEY_DELETE, Key::kDelete},
            {GLFW_KEY_END, Key::kEnd},
            {GLFW_KEY_ENTER, Key::kEnter},
            {GLFW_KEY_ESCAPE, Key::kEscape},
            {GLFW_KEY_HOME, Key::kHome},
            {GLFW_KEY_INSERT, Key::kInsert},
            {GLFW_KEY_MENU, Key::kMenu},
            {GLFW_KEY_PAGE_DOWN, Key::kPageDown},
            {GLFW_KEY_PAGE_UP, Key::kPageUp},
            {GLFW_KEY_PAUSE, Key::kPause},
            {GLFW_KEY_SPACE, Key::kSpace},
            {GLFW_KEY_TAB, Key::kTab},
            {GLFW_KEY_CAPS_LOCK, Key::kCapsLock},
            {GLFW_KEY_NUM_LOCK, Key::kNumLock},
            {GLFW_KEY_SCROLL_LOCK, Key::kScrollLock},

            {GLFW_KEY_F1, Key::kF1},
            {GLFW_KEY_F2, Key::kF2},
            {GLFW_KEY_F3, Key::kF3},
            {GLFW_KEY_F4, Key::kF4},
            {GLFW_KEY_F5, Key::kF5},
            {GLFW_KEY_F6, Key::kF6},
            {GLFW_KEY_F7, Key::kF7},
            {GLFW_KEY_F8, Key::kF8},
            {GLFW_KEY_F9, Key::kF9},
            {GLFW_KEY_F10, Key::kF10},
            {GLFW_KEY_F11, Key::kF11},
            {GLFW_KEY_F12, Key::kF12},
            {GLFW_KEY_F13, Key::kF13},
            {GLFW_KEY_F14, Key::kF14},
            {GLFW_KEY_F15, Key::kF15},
            {GLFW_KEY_F16, Key::kF16},
            {GLFW_KEY_F17, Key::kF17},
            {GLFW_KEY_F18, Key::kF18},
            {GLFW_KEY_F19, Key::kF19},
            {GLFW_KEY_F20, Key::kF20},
            {GLFW_KEY_F21, Key::kF21},
            {GLFW_KEY_F22, Key::kF22},
            {GLFW_KEY_F23, Key::kF23},
            {GLFW_KEY_F24, Key::kF24},

            {GLFW_KEY_LEFT_ALT, Key::kLeftAlt},
            {GLFW_KEY_LEFT_CONTROL, Key::kLeftControl},
            {GLFW_KEY_LEFT_SHIFT, Key::kLeftShift},
            {GLFW_KEY_LEFT_SUPER, Key::kLeftSuper},
            {GLFW_KEY_PRINT_SCREEN, Key::kPrintScreen},
            {GLFW_KEY_RIGHT_ALT, Key::kRightAlt},
            {GLFW_KEY_RIGHT_CONTROL, Key::kRightControl},
            {GLFW_KEY_RIGHT_SHIFT, Key::kRightShift},
            {GLFW_KEY_RIGHT_SUPER, Key::kRightSuper},

            {GLFW_KEY_DOWN, Key::kDown},
            {GLFW_KEY_LEFT, Key::kLeft},
            {GLFW_KEY_RIGHT, Key::kRight},
            {GLFW_KEY_UP, Key::kUp},

            {GLFW_KEY_KP_0, Key::kKeypad0},
            {GLFW_KEY_KP_1, Key::kKeypad1},
            {GLFW_KEY_KP_2, Key::kKeypad2},
            {GLFW_KEY_KP_3, Key::kKeypad3},
            {GLFW_KEY_KP_4, Key::kKeypad4},
            {GLFW_KEY_KP_5, Key::kKeypad5},
            {GLFW_KEY_KP_6, Key::kKeypad6},
            {GLFW_KEY_KP_7, Key::kKeypad7},
            {GLFW_KEY_KP_8, Key::kKeypad8},
            {GLFW_KEY_KP_9, Key::kKeypad9},
            {GLFW_KEY_KP_ADD, Key::kKeypadAdd},
            {GLFW_KEY_KP_DECIMAL, Key::kKeypadDecimal},
            {GLFW_KEY_KP_DIVIDE, Key::kKeypadDivide},
            {GLFW_KEY_KP_ENTER, Key::kKeypadEnter},
            {GLFW_KEY_KP_EQUAL, Key::kKeypadEqual},
            {GLFW_KEY_KP_MULTIPLY, Key::kKeypadMultiply},
            {GLFW_KEY_KP_SUBTRACT, Key::kKeypadSubtract},

            {GLFW_KEY_UNKNOWN, Key::kUnknown}};

        const std::unordered_map<Key, int> EngineKeyToGlfwKeycode = {
            {Key::k0, GLFW_KEY_0},
            {Key::k1, GLFW_KEY_1},
            {Key::k2, GLFW_KEY_2},
            {Key::k3, GLFW_KEY_3},
            {Key::k4, GLFW_KEY_4},
            {Key::k5, GLFW_KEY_5},
            {Key::k6, GLFW_KEY_6},
            {Key::k7, GLFW_KEY_7},
            {Key::k8, GLFW_KEY_8},
            {Key::k9, GLFW_KEY_9},
            {Key::kA, GLFW_KEY_A},
            {Key::kB, GLFW_KEY_B},
            {Key::kC, GLFW_KEY_C},
            {Key::kD, GLFW_KEY_D},
            {Key::kE, GLFW_KEY_E},
            {Key::kF, GLFW_KEY_F},
            {Key::kG, GLFW_KEY_G},
            {Key::kH, GLFW_KEY_H},
            {Key::kI, GLFW_KEY_I},
            {Key::kJ, GLFW_KEY_J},
            {Key::kK, GLFW_KEY_K},
            {Key::kL, GLFW_KEY_L},
            {Key::kM, GLFW_KEY_M},
            {Key::kN, GLFW_KEY_N},
            {Key::kO, GLFW_KEY_O},
            {Key::kP, GLFW_KEY_P},
            {Key::kQ, GLFW_KEY_Q},
            {Key::kR, GLFW_KEY_R},
            {Key::kS, GLFW_KEY_S},
            {Key::kT, GLFW_KEY_T},
            {Key::kU, GLFW_KEY_U},
            {Key::kV, GLFW_KEY_V},
            {Key::kW, GLFW_KEY_W},
            {Key::kX, GLFW_KEY_X},
            {Key::kY, GLFW_KEY_Y},
            {Key::kZ, GLFW_KEY_Z},

            {Key::kApostrophe, GLFW_KEY_APOSTROPHE},
            {Key::kBackslash, GLFW_KEY_BACKSLASH},
            {Key::kComma, GLFW_KEY_COMMA},
            {Key::kEqual, GLFW_KEY_EQUAL},
            {Key::kGraveAccent, GLFW_KEY_GRAVE_ACCENT},
            {Key::kLeftBracket, GLFW_KEY_LEFT_BRACKET},
            {Key::kMinus, GLFW_KEY_MINUS},
            {Key::kPeriod, GLFW_KEY_PERIOD},
            {Key::kRightBracket, GLFW_KEY_RIGHT_BRACKET},
            {Key::kSemicolon, GLFW_KEY_SEMICOLON},
            {Key::kSlash, GLFW_KEY_SLASH},
            {Key::kWorld2, GLFW_KEY_WORLD_2},

            {Key::kBackspace, GLFW_KEY_BACKSPACE},
            {Key::kDelete, GLFW_KEY_DELETE},
            {Key::kEnd, GLFW_KEY_END},
            {Key::kEnter, GLFW_KEY_ENTER},
            {Key::kEscape, GLFW_KEY_ESCAPE},
            {Key::kHome, GLFW_KEY_HOME},
            {Key::kInsert, GLFW_KEY_INSERT},
            {Key::kMenu, GLFW_KEY_MENU},
            {Key::kPageDown, GLFW_KEY_PAGE_DOWN},
            {Key::kPageUp, GLFW_KEY_PAGE_UP},
            {Key::kPause, GLFW_KEY_PAUSE},
            {Key::kSpace, GLFW_KEY_SPACE},
            {Key::kTab, GLFW_KEY_TAB},
            {Key::kCapsLock, GLFW_KEY_CAPS_LOCK},
            {Key::kNumLock, GLFW_KEY_NUM_LOCK},
            {Key::kScrollLock, GLFW_KEY_SCROLL_LOCK},

            {Key::kF1, GLFW_KEY_F1},
            {Key::kF2, GLFW_KEY_F2},
            {Key::kF3, GLFW_KEY_F3},
            {Key::kF4, GLFW_KEY_F4},
            {Key::kF5, GLFW_KEY_F5},
            {Key::kF6, GLFW_KEY_F6},
            {Key::kF7, GLFW_KEY_F7},
            {Key::kF8, GLFW_KEY_F8},
            {Key::kF9, GLFW_KEY_F9},
            {Key::kF10, GLFW_KEY_F10},
            {Key::kF11, GLFW_KEY_F11},
            {Key::kF12, GLFW_KEY_F12},
            {Key::kF13, GLFW_KEY_F13},
            {Key::kF14, GLFW_KEY_F14},
            {Key::kF15, GLFW_KEY_F15},
            {Key::kF16, GLFW_KEY_F16},
            {Key::kF17, GLFW_KEY_F17},
            {Key::kF18, GLFW_KEY_F18},
            {Key::kF19, GLFW_KEY_F19},
            {Key::kF20, GLFW_KEY_F20},
            {Key::kF21, GLFW_KEY_F21},
            {Key::kF22, GLFW_KEY_F22},
            {Key::kF23, GLFW_KEY_F23},
            {Key::kF24, GLFW_KEY_F24},

            {Key::kLeftAlt, GLFW_KEY_LEFT_ALT},
            {Key::kLeftControl, GLFW_KEY_LEFT_CONTROL},
            {Key::kLeftShift, GLFW_KEY_LEFT_SHIFT},
            {Key::kLeftSuper, GLFW_KEY_LEFT_SUPER},
            {Key::kPrintScreen, GLFW_KEY_PRINT_SCREEN},
            {Key::kRightAlt, GLFW_KEY_RIGHT_ALT},
            {Key::kRightControl, GLFW_KEY_RIGHT_CONTROL},
            {Key::kRightShift, GLFW_KEY_RIGHT_SHIFT},
            {Key::kRightSuper, GLFW_KEY_RIGHT_SUPER},

            {Key::kDown, GLFW_KEY_DOWN},
            {Key::kLeft, GLFW_KEY_LEFT},
            {Key::kRight, GLFW_KEY_RIGHT},
            {Key::kUp, GLFW_KEY_UP},

            {Key::kKeypad0, GLFW_KEY_KP_0},
            {Key::kKeypad1, GLFW_KEY_KP_1},
            {Key::kKeypad2, GLFW_KEY_KP_2},
            {Key::kKeypad3, GLFW_KEY_KP_3},
            {Key::kKeypad4, GLFW_KEY_KP_4},
            {Key::kKeypad5, GLFW_KEY_KP_5},
            {Key::kKeypad6, GLFW_KEY_KP_6},
            {Key::kKeypad7, GLFW_KEY_KP_7},
            {Key::kKeypad8, GLFW_KEY_KP_8},
            {Key::kKeypad9, GLFW_KEY_KP_9},
            {Key::kKeypadAdd, GLFW_KEY_KP_ADD},
            {Key::kKeypadDecimal, GLFW_KEY_KP_DECIMAL},
            {Key::kKeypadDivide, GLFW_KEY_KP_DIVIDE},
            {Key::kKeypadEnter, GLFW_KEY_KP_ENTER},
            {Key::kKeypadEqual, GLFW_KEY_KP_EQUAL},
            {Key::kKeypadMultiply, GLFW_KEY_KP_MULTIPLY},
            {Key::kKeypadSubtract, GLFW_KEY_KP_SUBTRACT},

            {Key::kUnknown, GLFW_KEY_UNKNOWN}};

        const std::string KeyToString(Key key)
        {
            switch (key)
            {
            case Key::k0:
                return "0";
            case Key::k1:
                return "1";
            case Key::k2:
                return "2";
            case Key::k3:
                return "3";
            case Key::k4:
                return "4";
            case Key::k5:
                return "5";
            case Key::k6:
                return "6";
            case Key::k7:
                return "7";
            case Key::k8:
                return "8";
            case Key::k9:
                return "9";

            case Key::kA:
                return "A";
            case Key::kB:
                return "B";
            case Key::kC:
                return "C";
            case Key::kD:
                return "D";
            case Key::kE:
                return "E";
            case Key::kF:
                return "F";
            case Key::kG:
                return "G";
            case Key::kH:
                return "H";
            case Key::kI:
                return "I";
            case Key::kJ:
                return "J";
            case Key::kK:
                return "K";
            case Key::kL:
                return "L";
            case Key::kM:
                return "M";
            case Key::kN:
                return "N";
            case Key::kO:
                return "O";
            case Key::kP:
                return "P";
            case Key::kQ:
                return "Q";
            case Key::kR:
                return "R";
            case Key::kS:
                return "S";
            case Key::kT:
                return "T";
            case Key::kU:
                return "U";
            case Key::kV:
                return "V";
            case Key::kW:
                return "W";
            case Key::kX:
                return "X";
            case Key::kY:
                return "Y";
            case Key::kZ:
                return "Z";

            case Key::kApostrophe:
                return "'";
            case Key::kBackslash:
                return "\\";
            case Key::kComma:
                return ",";
            case Key::kEqual:
                return "=";
            case Key::kGraveAccent:
                return "`";
            case Key::kLeftBracket:
                return "[";
            case Key::kMinus:
                return "-";
            case Key::kPeriod:
                return ".";
            case Key::kRightBracket:
                return "]";
            case Key::kSemicolon:
                return ";";
            case Key::kSlash:
                return "/";
            case Key::kWorld2:
                return "World2";

            case Key::kBackspace:
                return "Backspace";
            case Key::kDelete:
                return "Delete";
            case Key::kEnd:
                return "End";
            case Key::kEnter:
                return "Enter";
            case Key::kEscape:
                return "Escape";
            case Key::kHome:
                return "Home";
            case Key::kInsert:
                return "Insert";
            case Key::kMenu:
                return "Menu";
            case Key::kPageDown:
                return "PageDown";
            case Key::kPageUp:
                return "PageUp";
            case Key::kPause:
                return "Pause";
            case Key::kSpace:
                return "Space";
            case Key::kTab:
                return "Tab";

            case Key::kCapsLock:
                return "CapsLock";
            case Key::kNumLock:
                return "NumLock";
            case Key::kScrollLock:
                return "ScrollLock";

            case Key::kF1:
                return "F1";
            case Key::kF2:
                return "F2";
            case Key::kF3:
                return "F3";
            case Key::kF4:
                return "F4";
            case Key::kF5:
                return "F5";
            case Key::kF6:
                return "F6";
            case Key::kF7:
                return "F7";
            case Key::kF8:
                return "F8";
            case Key::kF9:
                return "F9";
            case Key::kF10:
                return "F10";
            case Key::kF11:
                return "F11";
            case Key::kF12:
                return "F12";
            case Key::kF13:
                return "F13";
            case Key::kF14:
                return "F14";
            case Key::kF15:
                return "F15";
            case Key::kF16:
                return "F16";
            case Key::kF17:
                return "F17";
            case Key::kF18:
                return "F18";
            case Key::kF19:
                return "F19";
            case Key::kF20:
                return "F20";
            case Key::kF21:
                return "F21";
            case Key::kF22:
                return "F22";
            case Key::kF23:
                return "F23";
            case Key::kF24:
                return "F24";

            case Key::kLeftAlt:
                return "LeftAlt";
            case Key::kLeftControl:
                return "LeftCtrl";
            case Key::kLeftShift:
                return "LeftShift";
            case Key::kLeftSuper:
                return "LeftSuper";
            case Key::kPrintScreen:
                return "PrintScreen";
            case Key::kRightAlt:
                return "RightAlt";
            case Key::kRightControl:
                return "RightCtrl";
            case Key::kRightShift:
                return "RightShift";
            case Key::kRightSuper:
                return "RightSuper";

            case Key::kDown:
                return "Down";
            case Key::kLeft:
                return "Left";
            case Key::kRight:
                return "Right";
            case Key::kUp:
                return "Up";

            case Key::kKeypad0:
                return "Keypad0";
            case Key::kKeypad1:
                return "Keypad1";
            case Key::kKeypad2:
                return "Keypad2";
            case Key::kKeypad3:
                return "Keypad3";
            case Key::kKeypad4:
                return "Keypad4";
            case Key::kKeypad5:
                return "Keypad5";
            case Key::kKeypad6:
                return "Keypad6";
            case Key::kKeypad7:
                return "Keypad7";
            case Key::kKeypad8:
                return "Keypad8";
            case Key::kKeypad9:
                return "Keypad9";
            case Key::kKeypadAdd:
                return "KeypadAdd";
            case Key::kKeypadDecimal:
                return "KeypadDecimal";
            case Key::kKeypadDivide:
                return "KeypadDivide";
            case Key::kKeypadEnter:
                return "KeypadEnter";
            case Key::kKeypadEqual:
                return "KeypadEqual";
            case Key::kKeypadMultiply:
                return "KeypadMultiply";
            case Key::kKeypadSubtract:
                return "KeypadSubtract";
            case Key::kUnknown:
                return "kUnknown";
            }

            return "Unknown";
        }
    }
}